const { Idea } = require("../Model");

const ideadata = [
  {
    title: "dragon game",
    coding_languages: "JAVASCRIPT",
    keywords: "entertainment, RPG, multiplayer",
    short_text: "An action role-laying game where the dragons control the humans.  Dragons collect and fight their humans across the world of Dragonia.",
    idea_type: "game",
    offer_type:"paid",
    offer_value: "20,000$ - 25,000$",
    text:"",
    userkey: 1,

  },
  {
    title: "movie_app",
    coding_languages: "C++",
    keywords: "entertainment, movies, film, pop-culture",
    short_text: "An app for determining what the best reviewed film of certain parameters are: year, rating, genre, etc.",
    idea_type: "app",
    offer_type:"paid",
    offer_value: "50,000$ - 75,000$",
    text:"",

    userkey: 2,
  },
  {
    title: "database",
    coding_languages: "JAVA",
    keywords: "data, comics",
    short_text: "I need some help getting my comic book collection online",
    idea_type: "program",
    offer_type:"paid",
    offer_value: "20,000$ - 25,000$",
    text:"",
    userkey: 3,
  },
  {
    title: "book_log",
    coding_languages: "JAVASCRIPT",
    keywords: "literature, books, library, personal",
    short_text: "I'm trying to organize the books I've read for my blog",
    idea_type: "website",
    offer_type:"free",
    offer_value: "",
    text:"I'm just getting the site off the ground, so while I couldn't pay now, I can easily pay if the site makes it big!",
    userkey: 4,
  },
  {
    title: "teachers_guide",
    coding_languages: "RUBY",
    keywords: "education",
    short_text: "my district is trying to make the online learning experience as engaging as possible through in-app communications with students.",
    idea_type: "app",
    offer_type:"paid",
    offer_value: "25,000$ - 50,000$",
    text:"",
    userkey: 5,
  },
  {
    title: "dating_app",
    coding_languages: "JAVASCRIPT",
    keywords: "dating, romance, love, relationships, matchmaking",
    short_text: "a combination of tinder and real matchmakers!",
    idea_type: "app",
    offer_type:"paid",
    offer_value: "250,000$ +",
    text:"",
    userkey: 6,
  },
  {
    title: "recipe blog",
    coding_languages: "HTML",
    keywords: "blog, text, journal, food, personal",
    short_text: "I love to cook, and I want to share my recipes.",
    idea_type: "website",
    offer_type:"paid",
    offer_value: "20,000$ - 25,000$",
    text:"",
    userkey: 7,
  },
  {
    title: "exercise_app",
    coding_languages: "TYPESCRIPT",
    keywords: "fitness, health, personal",
    short_text: "We want to make the process of choosing the correct weight for each exercise easy.",
    idea_type: "app",
    offer_type:"paid",
    offer_value: "50,000$ - 75,000$",
    text:"",
    userkey: 8,
  },
  {
    title: "money_saver",
    coding_languages: "PYTHON",
    keywords: "finance, savings, investment, personal",
    short_text: "Money is a scary subject, and we want to make it less scary.",
    idea_type: "app",
    offer_type:"partner",
    offer_value: "20,000$ - 25,000$",
    text:"",
    userkey: 9,
  },
  {
    title: "search_engine",
    coding_languages: "JAVASCRIPT",
    keywords: "search, query",
    short_text: "I want to work alongside some coders, to make an all-encompassing search engine that filters images alongside web-links.",
    idea_type: "website",
    offer_type:"partner",
    offer_value: "",
    text:"I think this could be something really big, and I want to find someone that can build this thing with me and see where it goes.",
    userkey: 10,
  },
];

const seedIdeas = () => Idea.bulkCreate(ideadata);

module.exports = seedIdeas;